<?xml version="1.0" encoding="utf-8"?><Database Name="CaPhe" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAMNGUYEN\SQLEXPRESS01;Initial Catalog=CaPhe;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CaPheConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CaPhe" Member="CaPhes">
    <Type Name="CaPhe">
      <Column Name="macaphe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maloai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="math" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tencaphe" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="hinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ngaycapnhat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CaPhe_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="macaphe" OtherKey="macaphe" Type="ChiTietDonHang" />
      <Association Name="LoaiCaPhe_CaPhe" Member="LoaiCaPhe" ThisKey="maloai" OtherKey="maloai" Type="LoaiCaPhe" IsForeignKey="true" />
      <Association Name="ThuongHieu_CaPhe" Member="ThuongHieu" ThisKey="math" OtherKey="math" Type="ThuongHieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="madon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="macaphe" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="CaPhe_ChiTietDonHang" Member="CaPhe" ThisKey="macaphe" OtherKey="macaphe" Type="CaPhe" IsForeignKey="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="madon" OtherKey="madon" Type="DonHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="madon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="thanhtoan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="giaohang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ngaydat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngaygiao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="makh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mapt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="madon" OtherKey="madon" Type="ChiTietDonHang" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="makh" OtherKey="makh" Type="KhachHang" IsForeignKey="true" />
      <Association Name="PhuongThucThanhToan_DonHang" Member="PhuongThucThanhToan" ThisKey="mapt" OtherKey="mapt" Type="PhuongThucThanhToan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="makh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="marole" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tendangnhap" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="dienthoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="makh" OtherKey="makh" Type="DonHang" />
      <Association Name="Role_KhachHang" Member="Role" ThisKey="marole" OtherKey="marole" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiCaPhe" Member="LoaiCaPhes">
    <Type Name="LoaiCaPhe">
      <Column Name="maloai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenloai" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="LoaiCaPhe_CaPhe" Member="CaPhes" ThisKey="maloai" OtherKey="maloai" Type="CaPhe" />
    </Type>
  </Table>
  <Table Name="dbo.PhuongThucThanhToan" Member="PhuongThucThanhToans">
    <Type Name="PhuongThucThanhToan">
      <Column Name="mapt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenpt" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="PhuongThucThanhToan_DonHang" Member="DonHangs" ThisKey="mapt" OtherKey="mapt" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="marole" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenrole" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Role_KhachHang" Member="KhachHangs" ThisKey="marole" OtherKey="marole" Type="KhachHang" />
    </Type>
  </Table>
  <Table Name="dbo.ThuongHieu" Member="ThuongHieus">
    <Type Name="ThuongHieu">
      <Column Name="math" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenth" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="ThuongHieu_CaPhe" Member="CaPhes" ThisKey="math" OtherKey="math" Type="CaPhe" />
    </Type>
  </Table>
</Database>